name: CI Pipeline 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push docker image
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
            IMAGE_NAME: pruthviraj3/img6    
        run: |
            docker build -t $IMAGE_NAME .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $IMAGE_NAME

      - name: Run tests using Docker image
        run: docker run $IMAGE_NAME python -m unittest discover
        