name: CI Pipeline 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push docker image
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
            IMAGE_NAME: pruthviraj3/img6    
        run: |
            docker build -t $IMAGE_NAME .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $IMAGE_NAME

     
      - name: set up kinD (Kubernetes in docker)
        uses: helm/kind-action@v1
        with: 
          version: latest
          node_image: kindest/node:v1.21.1
        

      # - name: Set up minikube
      #   run: |
      #     curl LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      #     sudo dpkg -i minikube_latest_amd64.deb

      - name: Deloy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml  