name: CI Pipeline 
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and push docker image
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
            IMAGE_NAME: pruthviraj3/img6    
        run: |
            docker build -t $IMAGE_NAME .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $IMAGE_NAME
        
      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Deploy to minikube
        run:
          kubectl apply -f deployment.yml
 
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      
      - name: Expose to service
        run:
          kubectl apply -f service.yml
 
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Test service URLs
        run: |
          kubectl get services
          kubectl get deployments
          kubectl get pods
 
          url=$(minikube service my-appservice --url)
 
          curl $url
          curl $url/ping
          curl $url/healthz
